// ============================================================
// PREP DATA — Structure for DSA & System Design learning paths
// Maps the docs/prep folder tree for sidebar navigation
// ============================================================

export const PREP_COURSES = [
  {
    id: "dsa",
    title: "DSA Mastery",
    subtitle: "12-Week FAANG Roadmap",
    icon: "code",
    color: "success",
    description: "Data Structures & Algorithms — pattern-based learning for FAANG interviews",
    basePath: "docs/prep/DSA",
    rootFiles: [
      { id: "dsa-readme", label: "README.md", file: "README.md", icon: "menu_book" },
      { id: "dsa-cheatsheet", label: "CHEATSHEET.md", file: "CHEATSHEET.md", icon: "bolt" },
    ],
    sections: [
      {
        id: "week-01",
        label: "Week 01 — Arrays & Complexity",
        icon: "view_array",
        folder: "Week-01-Arrays-Complexity",
        files: [
          { id: "w01-readme", label: "README.md", file: "README.md" },
          { id: "w01-big-o", label: "Big O Notation", file: "01-Big-O-Notation/big_o_explained.md" },
          { id: "w01-arrays", label: "Array Basics", file: "02-Array-Implementation/array_basics.md" },
          { id: "w01-prefix", label: "Prefix Sum", file: "03-Prefix-Sum/prefix_sum.md" },
          { id: "w01-cyclic", label: "Cyclic Sort", file: "04-Cyclic-Sort/cyclic_sort.md" },
        ],
      },
      {
        id: "week-02",
        label: "Week 02 — Strings & Hashing",
        icon: "text_fields",
        folder: "Week-02-Strings-Hashing",
        files: [
          { id: "w02-readme", label: "README.md", file: "README.md" },
          { id: "w02-strings", label: "String Fundamentals", file: "01-String-Basics/string_fundamentals.md" },
          { id: "w02-hashmap", label: "HashMap Explained", file: "02-HashMap-Implementation/hashmap_explained.md" },
        ],
      },
      {
        id: "week-03",
        label: "Week 03 — Stacks & Queues",
        icon: "stacked_bar_chart",
        folder: "Week-03-Stacks-Queues",
        files: [
          { id: "w03-readme", label: "README.md", file: "README.md" },
          { id: "w03-stack", label: "Stack Explained", file: "01-Stack-Implementation/stack_explained.md" },
          { id: "w03-queue", label: "Queue Explained", file: "02-Queue-Implementation/queue_explained.md" },
        ],
      },
      {
        id: "week-04",
        label: "Week 04 — Linked Lists",
        icon: "link",
        folder: "Week-04-Linked-Lists",
        files: [
          { id: "w04-readme", label: "README.md", file: "README.md" },
        ],
      },
      {
        id: "week-05",
        label: "Week 05 — Two Pointers",
        icon: "compare_arrows",
        folder: "Week-05-Two-Pointers",
        files: [
          { id: "w05-readme", label: "README.md", file: "README.md" },
          { id: "w05-pattern", label: "Two Pointers Explained", file: "01-Pattern-Intuition/two_pointers_explained.md" },
        ],
      },
      {
        id: "week-06",
        label: "Week 06 — Sliding Window",
        icon: "width",
        folder: "Week-06-Sliding-Window",
        files: [
          { id: "w06-readme", label: "README.md", file: "README.md" },
          { id: "w06-pattern", label: "Sliding Window Explained", file: "01-Pattern-Intuition/sliding_window_explained.md" },
        ],
      },
      {
        id: "week-07",
        label: "Week 07 — Binary Search",
        icon: "search",
        folder: "Week-07-Binary-Search",
        files: [
          { id: "w07-readme", label: "README.md", file: "README.md" },
          { id: "w07-pattern", label: "Binary Search Explained", file: "01-Pattern-Intuition/binary_search_explained.md" },
        ],
      },
      {
        id: "week-08",
        label: "Week 08 — Sorting & Intervals",
        icon: "sort",
        folder: "Week-08-Sorting-Intervals",
        files: [
          { id: "w08-readme", label: "README.md", file: "README.md" },
          { id: "w08-sorting", label: "Sorting Explained", file: "01-Sorting-Algorithms/sorting_explained.md" },
          { id: "w08-intervals", label: "Intervals Explained", file: "02-Interval-Patterns/intervals_explained.md" },
        ],
      },
      {
        id: "week-09",
        label: "Week 09 — Trees",
        icon: "account_tree",
        folder: "Week-09-Trees",
        files: [
          { id: "w09-readme", label: "README.md", file: "README.md" },
          { id: "w09-trees", label: "Trees Explained", file: "01-Tree-Fundamentals/trees_explained.md" },
          { id: "w09-bst", label: "BST Explained", file: "02-BST-Operations/bst_explained.md" },
        ],
      },
      {
        id: "week-10",
        label: "Week 10 — Graphs",
        icon: "hub",
        folder: "Week-10-Graphs",
        files: [
          { id: "w10-readme", label: "README.md", file: "README.md" },
          { id: "w10-graphs", label: "Graphs Explained", file: "01-Graph-Fundamentals/graphs_explained.md" },
          { id: "w10-topo", label: "Topological & Union Find", file: "03-Algorithms/topological_union_find.md" },
        ],
      },
      {
        id: "week-11",
        label: "Week 11 — Dynamic Programming",
        icon: "grid_on",
        folder: "Week-11-Dynamic-Programming",
        files: [
          { id: "w11-readme", label: "README.md", file: "README.md" },
          { id: "w11-dp", label: "DP Explained", file: "01-DP-Fundamentals/dp_explained.md" },
          { id: "w11-knapsack", label: "Knapsack Pattern", file: "04-Knapsack-Pattern/knapsack_explained.md" },
          { id: "w11-string-dp", label: "String DP", file: "05-String-DP/string_dp.md" },
        ],
      },
      {
        id: "week-12",
        label: "Week 12 — Advanced & Revision",
        icon: "trophy",
        folder: "Week-12-Advanced-Revision",
        files: [
          { id: "w12-readme", label: "README.md", file: "README.md" },
          { id: "w12-backtrack", label: "Backtracking Explained", file: "01-Backtracking/backtracking_explained.md" },
          { id: "w12-heap", label: "Heap Explained", file: "02-Heap/heap_explained.md" },
          { id: "w12-trie", label: "Trie Explained", file: "04-Trie/trie_explained.md" },
          { id: "w12-cheatsheet", label: "Pattern Cheatsheet", file: "06-Interview-Prep/pattern_cheatsheet.md" },
        ],
      },
      {
        id: "problems",
        label: "Practice Problems",
        icon: "quiz",
        folder: "Problems",
        subsections: [
          { id: "p01", label: "01 — Arrays & Hashing", folder: "01-Arrays-Hashing", indexFile: "arrays_hashing_problems.md" },
          { id: "p02", label: "02 — Two Pointers", folder: "02-Two-Pointers", indexFile: "two_pointers_problems.md" },
          { id: "p03", label: "03 — Sliding Window", folder: "03-Sliding-Window", indexFile: "sliding_window_problems.md" },
          { id: "p04", label: "04 — Stack", folder: "04-Stack", indexFile: "stack_problems.md" },
          { id: "p05", label: "05 — Binary Search", folder: "05-Binary-Search", indexFile: "binary_search_problems.md" },
          { id: "p06", label: "06 — Linked List", folder: "06-Linked-List", indexFile: "linked_list_problems.md" },
          { id: "p07", label: "07 — Trees", folder: "07-Trees", indexFile: "trees_problems.md" },
          { id: "p08", label: "08 — Heap", folder: "08-Heap", indexFile: "heap_problems.md" },
          { id: "p09", label: "09 — Backtracking", folder: "09-Backtracking", indexFile: "backtracking_problems.md" },
          { id: "p10", label: "10 — Tries", folder: "10-Tries", indexFile: "tries_problems.md" },
          { id: "p11", label: "11 — Graphs", folder: "11-Graphs", indexFile: "graphs_problems.md" },
          { id: "p12", label: "12 — Advanced Graphs", folder: "12-Advanced-Graphs", indexFile: "advanced_graphs_problems.md" },
          { id: "p13", label: "13 — 1D DP", folder: "13-1D-DP", indexFile: "1d_dp_problems.md" },
          { id: "p14", label: "14 — 2D DP", folder: "14-2D-DP", indexFile: "2d_dp_problems.md" },
          { id: "p15", label: "15 — Greedy", folder: "15-Greedy", indexFile: "greedy_problems.md" },
          { id: "p16", label: "16 — Intervals", folder: "16-Intervals", indexFile: "intervals_problems.md" },
          { id: "p17", label: "17 — Math & Geometry", folder: "17-Math-Geometry", indexFile: "math_geometry_problems.md" },
          { id: "p18", label: "18 — Bit Manipulation", folder: "18-Bit-Manipulation", indexFile: "bit_manipulation_problems.md" },
        ],
      },
    ],
  },
  {
    id: "system-design",
    title: "System Design",
    subtitle: "RESHADED Framework",
    icon: "architecture",
    color: "accent",
    description: "System Design mastery — from fundamentals to real-world case studies",
    basePath: "docs/prep/System Design",
    rootFiles: [
      { id: "sd-readme", label: "README.md", file: "README.md", icon: "menu_book" },
      { id: "sd-cheatsheet", label: "CHEATSHEET.md", file: "CHEATSHEET.md", icon: "bolt" },
    ],
    sections: [
      {
        id: "sd-fundamentals",
        label: "01 — Fundamentals",
        icon: "foundation",
        folder: "01-Fundamentals",
        files: [
          { id: "f-readme", label: "README.md", file: "README.md" },
          { id: "f-intro", label: "Introduction", file: "01-introduction.md" },
          { id: "f-abstractions", label: "Abstractions", file: "02-abstractions.md" },
          { id: "f-rpc", label: "Network & RPC", file: "03-network-abstractions-rpc.md" },
          { id: "f-consistency", label: "Consistency Models", file: "04-consistency-models.md" },
          { id: "f-failures", label: "Failure Models", file: "05-failure-models.md" },
        ],
      },
      {
        id: "sd-nfr",
        label: "02 — Non-Functional Requirements",
        icon: "verified",
        folder: "02-Non-Functional-Requirements",
        files: [
          { id: "nfr-readme", label: "README.md", file: "README.md" },
          { id: "nfr-avail", label: "Availability", file: "01-availability.md" },
          { id: "nfr-reliab", label: "Reliability", file: "02-reliability.md" },
          { id: "nfr-scale", label: "Scalability", file: "03-scalability.md" },
          { id: "nfr-maintain", label: "Maintainability", file: "04-maintainability.md" },
          { id: "nfr-fault", label: "Fault Tolerance", file: "05-fault-tolerance.md" },
        ],
      },
      {
        id: "sd-estimation",
        label: "03 — Estimation",
        icon: "calculate",
        folder: "03-Estimation",
        files: [
          { id: "est-readme", label: "README.md", file: "README.md" },
          { id: "est-numbers", label: "Numbers to Know", file: "01-numbers-to-know.md" },
          { id: "est-resources", label: "Resource Estimation", file: "02-resource-estimation-examples.md" },
          { id: "est-interview", label: "Interview Examples", file: "03-interview-examples.md" },
        ],
      },
      {
        id: "sd-building-blocks",
        label: "04 — Building Blocks",
        icon: "widgets",
        folder: "04-Building-Blocks",
        files: [
          { id: "bb-readme", label: "README.md", file: "README.md" },
          { id: "bb-dns", label: "DNS", file: "01-dns.md" },
          { id: "bb-lb", label: "Load Balancers", file: "02-load-balancers.md" },
          { id: "bb-db", label: "Databases", file: "03-databases.md" },
          { id: "bb-kv", label: "Key-Value Stores", file: "04-key-value-stores.md" },
          { id: "bb-cdn", label: "CDN", file: "05-cdn.md" },
          { id: "bb-seq", label: "Sequencer", file: "06-sequencer.md" },
          { id: "bb-cache", label: "Distributed Cache", file: "07-distributed-cache.md" },
          { id: "bb-mq", label: "Message Queues", file: "08-message-queues.md" },
          { id: "bb-pubsub", label: "Pub/Sub", file: "09-pub-sub.md" },
          { id: "bb-rl", label: "Rate Limiter", file: "10-rate-limiter.md" },
          { id: "bb-blob", label: "Blob Store", file: "11-blob-store.md" },
          { id: "bb-search", label: "Distributed Search", file: "12-distributed-search.md" },
          { id: "bb-logging", label: "Distributed Logging", file: "13-distributed-logging.md" },
          { id: "bb-monitor", label: "Distributed Monitoring", file: "14-distributed-monitoring.md" },
          { id: "bb-scheduler", label: "Task Scheduler", file: "15-task-scheduler.md" },
          { id: "bb-counters", label: "Sharded Counters", file: "16-sharded-counters.md" },
        ],
      },
      {
        id: "sd-design-problems",
        label: "05 — Design Problems",
        icon: "draw",
        folder: "05-Design-Problems",
        files: [
          { id: "dp-readme", label: "README.md", file: "README.md" },
          { id: "dp-tinyurl", label: "TinyURL", file: "01-tinyurl.md" },
          { id: "dp-twitter", label: "Twitter", file: "02-twitter.md" },
          { id: "dp-instagram", label: "Instagram", file: "03-instagram.md" },
          { id: "dp-whatsapp", label: "WhatsApp", file: "04-whatsapp.md" },
          { id: "dp-youtube", label: "YouTube", file: "05-youtube.md" },
          { id: "dp-newsfeed", label: "News Feed", file: "06-newsfeed.md" },
          { id: "dp-uber", label: "Uber", file: "07-uber.md" },
          { id: "dp-maps", label: "Google Maps", file: "08-google-maps.md" },
          { id: "dp-yelp", label: "Yelp", file: "09-yelp.md" },
          { id: "dp-typeahead", label: "Typeahead", file: "10-typeahead.md" },
          { id: "dp-crawler", label: "Web Crawler", file: "11-web-crawler.md" },
          { id: "dp-docs", label: "Google Docs", file: "12-google-docs.md" },
          { id: "dp-quora", label: "Quora", file: "13-quora.md" },
          { id: "dp-payment", label: "Payment System", file: "14-payment-system.md" },
          { id: "dp-deploy", label: "Deployment System", file: "15-deployment-system.md" },
          { id: "dp-chatgpt", label: "ChatGPT", file: "16-chatgpt.md" },
        ],
      },
      {
        id: "sd-case-studies",
        label: "06 — Case Studies",
        icon: "cases",
        folder: "06-Case-Studies",
        files: [
          { id: "cs-readme", label: "README.md", file: "README.md" },
          { id: "cs-spotify", label: "Spotify", file: "01-spotify.md" },
          { id: "cs-netflix", label: "Netflix", file: "02-netflix.md" },
          { id: "cs-chatgpt", label: "ChatGPT", file: "03-chatgpt.md" },
          { id: "cs-ticketmaster", label: "Ticketmaster", file: "04-ticketmaster.md" },
          { id: "cs-failures", label: "System Failures", file: "05-system-failures.md" },
          { id: "cs-rate-limiter", label: "Rate Limiter", file: "06-rate-limiter.md" },
          { id: "cs-tinyurl", label: "TinyURL", file: "07-tinyurl.md" },
          { id: "cs-twitter", label: "Twitter", file: "08-twitter.md" },
          { id: "cs-discord", label: "Discord", file: "09-discord.md" },
          { id: "cs-youtube", label: "YouTube", file: "10-youtube.md" },
          { id: "cs-drive", label: "Google Drive", file: "11-google-drive.md" },
          { id: "cs-maps", label: "Google Maps", file: "12-google-maps.md" },
          { id: "cs-kv-store", label: "Key-Value Store", file: "13-key-value-store.md" },
          { id: "cs-mq", label: "Message Queue", file: "14-message-queue.md" },
          { id: "cs-whatsapp", label: "WhatsApp", file: "15-whatsapp.md" },
          { id: "cs-gmail", label: "Gmail", file: "16-gmail.md" },
          { id: "cs-tinder", label: "Tinder", file: "17-tinder.md" },
          { id: "cs-parking", label: "Parking Lot", file: "18-parking-lot.md" },
          { id: "cs-hotstar", label: "Hotstar", file: "19-hotstar.md" },
          { id: "cs-gdocs", label: "Google Docs", file: "20-google-docs.md" },
          { id: "cs-uber", label: "Uber", file: "21-uber.md" },
          { id: "cs-wa-call", label: "WhatsApp Calling", file: "22-whatsapp-calling.md" },
          { id: "cs-zoom", label: "Zoom", file: "23-zoom.md" },
          { id: "cs-recsys", label: "Recommendation Engine", file: "24-recommendation-engine.md" },
        ],
      },
    ],
  },
];
